import { StyleSheet } from 'react-native';
import { Platform } from 'react-native';

const ChatBoxStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f0fdf4',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        paddingTop: Platform.OS === 'android' ? 45 : 12,
        backgroundColor: '#16a34a',
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    backButton: {
        padding: 8,
    },
    headerContent: {
        flex: 1,
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
        letterSpacing: 1,
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#e2f4e2',
        marginTop: 2,
    },
    menuButton: {
        padding: 8,
    },
    listContent: {
        padding: 12,
        paddingBottom: 100,
    },
    welcomeBanner: {
        alignItems: 'center',
        marginBottom: 20,
        marginTop: 10,
    },
    welcomeImage: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#dcfce7',
    },
    welcomeText: {
        marginTop: 12,
        fontSize: 16,
        color: '#15803d',
        fontWeight: '600',
    },
    messageContainer: {
        flexDirection: 'row',
        marginBottom: 12,
        maxWidth: '100%',
    },
    userContainer: {
        justifyContent: 'flex-end',
    },
    botContainer: {
        justifyContent: 'flex-start',
    },
    avatarContainer: {
        marginRight: 8,
        alignSelf: 'flex-end',
        marginBottom: 18,
    },
    avatar: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#16a34a',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#dcfce7',
    },
    bubbleWrapper: {
        maxWidth: '80%',
    },
    userBubbleWrapper: {
        alignItems: 'flex-end',
    },
    botBubbleWrapper: {
        alignItems: 'flex-start',
    },
    userBubble: {
        backgroundColor: '#16a34a',
        borderRadius: 18,
        borderBottomRightRadius: 4,
        padding: 12,
        paddingBottom: 18,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 1,
    },
    botBubble: {
        backgroundColor: '#ffffff',
        borderRadius: 18,
        borderBottomLeftRadius: 4,
        padding: 12,
        paddingBottom: 18,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 1,
    },
    userText: {
        color: '#ffffff',
        fontSize: 16,
    },
    botText: {
        color: '#1e293b',
        fontSize: 16,
    },
    timestamp: {
        fontSize: 10,
        position: 'absolute',
        bottom: 4,
        right: 8,
    },
    userTimestamp: {
        color: '#dcfce7',
    },
    botTimestamp: {
        color: '#94a3b8',
    },
    messageImage: {
        width: 200,
        height: 200,
        borderRadius: 12,
        marginBottom: 6,
    },
    imageCaption: {
        marginTop: 6,
    },
    typingContainer: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        marginLeft: 12,
        marginBottom: 12,
    },
    typingAvatar: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#16a34a',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    typingBubble: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        borderBottomLeftRadius: 4,
        padding: 12,
        width: 64,
        flexDirection: 'row',
        justifyContent: 'center',
    },
    typingDots: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    typingDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#16a34a',
        marginHorizontal: 2,
        opacity: 0.6,
    },
    typingDot1: {
        animationName: 'bounce',
        animationDuration: '0.8s',
        animationDelay: '0s',
        animationIterationCount: 'infinite',
    },
    typingDot2: {
        animationName: 'bounce',
        animationDuration: '0.8s',
        animationDelay: '0.2s',
        animationIterationCount: 'infinite',
    },
    typingDot3: {
        animationName: 'bounce',
        animationDuration: '0.8s',
        animationDelay: '0.4s',
        animationIterationCount: 'infinite',
    },
    pendingImageContainer: {
        alignSelf: 'flex-end',
        marginRight: 16,
        marginBottom: 8,
    },
    pendingImageWrapper: {
        position: 'relative',
    },
    pendingImage: {
        width: 90, 
        height: 90, 
        borderRadius: 14, 
        borderWidth: 2, 
        borderColor: '#16a34a',
    },
    removeImageButton: {
        position: 'absolute', 
        top: -8, 
        right: -8, 
        backgroundColor: '#fff', 
        borderRadius: 12, 
        padding: 2,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderTopWidth: 1,
        borderColor: '#e5e7eb',
        backgroundColor: '#fff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 3,
    },
    cameraButton: {
        padding: 10,
        backgroundColor: '#f0fdf4',
        borderRadius: 20,
        marginRight: 8,
    },
    textInput: {
        flex: 1,
        backgroundColor: '#f5f5f5',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#d1fae5',
        paddingHorizontal: 16,
        paddingVertical: 8,
        maxHeight: 100,
        fontSize: 16,
        color: '#333',
    },
    sendButton: {
        marginLeft: 8,
        backgroundColor: '#16a34a',
        borderRadius: 20,
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sendButtonDisabled: {
        backgroundColor: '#a3e635',
        opacity: 0.7,
    },
    inputFooter: {
        alignItems: 'center',
        paddingVertical: 4,
        backgroundColor: '#fff',
    },
    poweredBy: {
        fontSize: 10,
        color: '#94a3b8',
    },
    dayContainer: {
        alignItems: 'center',
        marginVertical: 12,
    },
    dayText: {
        fontSize: 12,
        color: '#64748b',
        backgroundColor: '#e2f4e2',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 10,
        overflow: 'hidden',
    },
});

export default ChatBoxStyles;